---
- name: Install neovim dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ninja-build
    - gettext
    - cmake
    - curl
    - build-essential
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - g++
    - pkg-config
    - unzip

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim'
    dest: /tmp/neovim/
    single_branch: true
    version: master

- name: Build nvim release version
  community.general.make:
    chdir: /tmp/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install nvim release version
  become: true
  community.general.make:
    chdir: /tmp/neovim
    target: install

# - name: Install pynvim
#   ansible.builtin.pip:
#     name:
#       - pynvim
#     state: present
#     executable: pip3

- name: Generate :help pages
  ansible.builtin.shell: nvim --headless -c 'helptags ALL' -c quit

- name: Install Treesitter parsers
  ansible.builtin.shell: nvim --headless -c 'TSUpdateSync' -c quit
